In [5]:
import re
import numpy as np
import pandas as pd
from sklearn.ensemble import VotingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [6]:
fake_df=pd.read_csv('Fake.csv')
true_df=pd.read_csv('True.csv')
fake_df=fake_df.drop(['date','subject'],axis=1)
true_df=true_df.drop(['date','subject'],axis=1)
fake_df['label'],true_df['label']=0,1
fake_df.head()
true_df.head()

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,1

In [7]:
def clean(text):

    text=text.lower()
    text=re.sub(r'http\S+|www\S+', '', text)
    text=re.sub(r'<.*?>', '', text)
    text=re.sub(r'[^a-z\s]', '', text)
    text=re.sub(r'\s+', ' ', text).strip()
    return text

In [8]:
fake_df['title']=fake_df['title'].apply(clean)
fake_df['text']=fake_df['text'].apply(clean)
true_df['title']=true_df['title'].apply(clean)
true_df['text']=true_df['text'].apply(clean)

In [9]:
df=pd.concat([fake_df,true_df],ignore_index=True)
df['content']=df['title']+" "+df['text']
df=df.drop(['title','text'],axis=1)
df.head()

   label                                            content
0      0  donald trump sends out embarrassing new years ...
1      0  drunk bragging trump staffer started russian c...
2      0  sheriff david clarke becomes an internet joke ...
3      0  trump is so obsessed he even has obamas name c...
4      0  pope francis just called out donald trump duri...

In [10]:
x=df['content']
y=df['label']
x.head()
y.head()
y.unique()

array([0, 1])

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=20)

In [12]:
tfidf=TfidfVectorizer(max_features=5000)
x_train=tfidf.fit_transform(x_train)
x_test=tfidf.transform(x_test)

In [13]:
np.unique(x_train.data)

array([0.00130014, 0.00136971, 0.0015984 , ..., 0.84826272, 0.86526613,
       0.99285694], shape=(4177129,))