In [1]:
import re
import pandas as pd
from sklearn.ensemble import VotingClassifier

In [15]:
fake_df=pd.read_csv('Fake.csv')
true_df=pd.read_csv('True.csv')
fake_df=fake_df.drop(['date','subject'],axis=1)
true_df=true_df.drop(['date','subject'],axis=1)
fake_df['label'],true_df['label']=0,1
fake_df.head()
true_df.head()

                                               title  ... label
0  As U.S. budget fight looms, Republicans flip t...  ...     1
1  U.S. military to accept transgender recruits o...  ...     1
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...     1
3  FBI Russia probe helped by Australian diplomat...  ...     1
4  Trump wants Postal Service to charge 'much mor...  ...     1

[5 rows x 3 columns]

In [16]:
def clean(text):

    text=text.lower()
    text=re.sub(r'http\S+|www\S+', '', text)
    text=re.sub(r'<.*?>', '', text)
    text=re.sub(r'[^a-z\s]', '', text)
    text=re.sub(r'\s+', ' ', text).strip()
    return text

In [21]:
fake_df['title']=fake_df['title'].apply(clean)
fake_df['text']=fake_df['text'].apply(clean)
true_df['title']=true_df['title'].apply(clean)
true_df['text']=true_df['text'].apply(clean)

In [22]:
fake_df.head()
true_df.head()

                                               title  ... label
0  as us budget fight looms republicans flip thei...  ...     1
1  us military to accept transgender recruits on ...  ...     1
2  senior us republican senator let mr mueller do...  ...     1
3  fbi russia probe helped by australian diplomat...  ...     1
4  trump wants postal service to charge much more...  ...     1

[5 rows x 3 columns]